package com.junior.AgroManager.enums;

public enum AgroEventType {

    SEASON_CREATED,
    SEASON_STARTED,
    SEASON_COMPLETED,

    APPLICATION_CREATED,
    APPLICATION_COMPLETED,

    RECOMMENDATION_CREATED,
    RECOMMENDATION_APPROVED,

    STOCK_UPDATED,
    STOCK_LOW,

    PURCHASE_CREATED,
    PURCHASE_RECEIVED,

    HARVEST_STARTED,
    HARVEST_COMPLETED,

    USER_CREATED
}